---
phases: 
  build: 
    commands: 
      - "echo Build started on `date`"
      - "echo Building the Docker image..."
      - "docker build -t react-frontend ."
      - "docker tag react-frontend 740126133497.dkr.ecr.eu-north-1.amazonaws.com/insight_front"
  post_build: 
    commands: 
      - "echo Build completed on `date`"
      - "echo Pushing the Docker image..."
      - "docker push 740126133497.dkr.ecr.eu-north-1.amazonaws.com/insight_front"
  pre_build: 
    commands: 
      - "echo Logging in to AWS..."
      - "docker login -u AWS -p eyJwYXlsb2FkIjoiZnYrNzNtWHIraWJPbDMvL0NkUm1PNkRSUFhSYkIvUHFCUXhPSUVITTNlQVRCKzVMbDRjNWI0dWFrblVPMzdhdEtMSEl0TDJHd0VqbUExdmM3VnZqb0hlc3dvRHVRUjZ4NllTZU9MWVNaR3RVbXdPVGlXaXRJc1VuYWNBSU1mMTBjNURaTGlLWk0rSUFyb3pDUXFIek44aDkyNno4elp4S3pneGptRzB4WTlBU0RXcUpCd25ZN3IrQng5VEUwVGZieDFFVzhJSHVlRmRCOVJEZXVDRjdHc2hnc05MMWpNYlM5YXBiL0hqY25PK0xwTTZKSEFFUzg2Tjh6N1lWZ3R3bDdwUWxDSGUzb0hFcVQ3MUFzS3VWdytMQ1NwTmV5QW83cWpWTlhPNzdYVHZwbHZsUzRRMm9XTEhzciswVkxpODdSQkU2WkxEZFBUWC82WVpIcXRraTJ0aExQMjJYenB5QmJ1K1Y5bWVZb05KaDMxQ3gwOEh5WEdidjd2dUQ3TENwbmtlY1UyWnVVQmE5dmdMejFDN293TGJ4NmN5V2YxNFpGT1lNVDluQVA4THpGem1XOTJIRVZvc1ZjRVNXWEJ2R1krc09zV0lheE96dVZXbWpDdHdNaWxyNldGMGFKMkFtTjZIc2svQkV4cEVnZURzcS9pRjlNNWovM2thenR5eU4xdzNGM2lIcm5TcWt5M3NXd3hIeEZPL29uUXVtVWJUd2FTNGVVcnZJcnB4YWdUdU1yZTRuZU9KUEZMN2ZyR09oREszNXZjdVVtVjQwN2ZFMnhCWGE0b3VyNFJVbGE1KzhkQjhQTjlUT0JtR2VaWjJaQWhxVlR0YmFvalk4SjBRRm5hT1FaSUErYzFBWk55bzF5c3ZvUFUwVGNrUG1lanVlbHdUOUxoOENrZGdaSVpFa1NOSmdDZHBqdkFkQXZxWVJBVGc0Y3FibVY5WGdGNmt1akhtODQ4N1RsUVFodmJuR2NVRjQ1TnBETThNMkhnZW1zcjBFZ2lsUUdnMTkzY3JnOW51Njk5NWE4d2hTRDhha0hiWVU0OVJBallmRFNMVlFqSStrSFRTWDRHUTV3V05JUmNLY05YWkVCQzdiTmpXcnM0TERiZG1nZFl2czdpQndCanNjOTRmUEQweWI1UFFCQ2J5eHVyc1hnQlJJd0RCdE5wNk9PNDkxVVpxRUxDTDJiWUdWOFZqMVAvd05YYXh6TnE0cDNETi9neFJhZ3RlMEtJTXhoaHZlOG16aUFodGxiRFVBSjRPQlVPdENocFpIckg1RFNuMzRCQyt6ZGZOMG9hU1JrZ3lhd0liYmFJMHlvbUVJd3gyYUluaC9UYjh3blR5cHFRd3JwTTdmQWcvVS84ZUFoTnJtYno5V28vVS9RTFN0TThzUWk3TmlSeitMbS91Z1RBTFNrWXc5U1B3TkRxczlHbERRbWpRZ1h5bXJNdXEzcEFXVDZtai9henNwWUE9PSIsImRhdGFrZXkiOiJBUUlCQUhoZnJGUTJhSUl3RjVWYzc5UkhFUEduY1VXdXIyL0p6TTh0L1p6b0V0UnJBZ0hNYkN6cTRqL3VZZHczRXhXYitLODlBQUFBZmpCOEJna3Foa2lHOXcwQkJ3YWdiekJ0QWdFQU1HZ0dDU3FHU0liM0RRRUhBVEFlQmdsZ2hrZ0JaUU1FQVM0d0VRUU1YaTlPNWZzQmZ3QVdOd1NBQWdFUWdEdkFyZHlRK240MFh3WTN4R0xCU3VPeGt6TzRNeFNkUTQzWm1jMlQreTBZa21qN0QwSk1ZaG12Qkh3Uk50NlZRK3FTLzZLVEhHeGZiNG53eVE9PSIsInZlcnNpb24iOiIyIiwidHlwZSI6IkRBVEFfS0VZIiwiZXhwaXJhdGlvbiI6MTYxNjEwMDM4Mn0= 740126133497.dkr.ecr.eu-north-1.amazonaws.com"
artifacts:
  files: 
    - "**/*"
  name: "s3-to-s3-latest-build.zip" 
version: 0.1
